services:
  - type: web
    name: vehicle-service-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ./mvnw clean install
    startCommand: java -jar app.jar
    envVars:
      - key: DB_URL
        value: jdbc:mysql://<HOST>:3306/vsmsdb
      - key: DB_USERNAME
        value: vsmsdb
      - key: DB_PASSWORD
        value: Shubham@123
